//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA99AI.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA99AI.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the used values is not correct!.
        /// </summary>
        internal static string FrmMain_Message_One_Of_The_Used_Values_Is_Not_Correct {
            get {
                return ResourceManager.GetString("FrmMain_Message_One_Of_The_Used_Values_Is_Not_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Message_Statique_Equivalente_Methode_Cannot_Be_Used_Fr {
            get {
                return ResourceManager.GetString("FrmMain_Message_Statique_Equivalente_Methode_Cannot_Be_Used_Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Type_d_ouvrage {
            get {
                return ResourceManager.GetString("FrmMain_Type_d_ouvrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_A_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_A_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Beta_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Beta_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Ct_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Ct_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Dx_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Dx_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Dy_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Dy_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Eta_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Eta_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Q_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Q_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_R_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_R_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_T1_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_T1_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_T2_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_T2_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Tx_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Tx_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Ty_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Ty_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Vx_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Vx_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Vx08_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Vx08_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Vy_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Vy_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Vy08_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Vy08_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_W_Rquals {
            get {
                return ResourceManager.GetString("FrmMain_Value_W_Rquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FrmMain_Value_Xi_Equals {
            get {
                return ResourceManager.GetString("FrmMain_Value_Xi_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgClose {
            get {
                object obj = ResourceManager.GetObject("ImgClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgHelp {
            get {
                object obj = ResourceManager.GetObject("ImgHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgInfo {
            get {
                object obj = ResourceManager.GetObject("ImgInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSave {
            get {
                object obj = ResourceManager.GetObject("ImgSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgSettings {
            get {
                object obj = ResourceManager.GetObject("ImgSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
