//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA99AI.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbSite_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbSite_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbSite_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbZone_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbZone_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbZone_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbWilaya_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbWilaya_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbWilaya_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbMateriau_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbMateriau_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbMateriau_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbImportance_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbImportance_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbImportance_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbTypeOuvrage_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbTypeOuvrage_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbTypeOuvrage_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbFormuleFond_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbFormuleFond_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbFormuleFond_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbFormuleEmpirique_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbFormuleEmpirique_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbFormuleEmpirique_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbSysContreventement_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbSysContreventement_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbSysContreventement_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMain_CmbSysContreventementStat_SelectedIndex {
            get {
                return ((int)(this["FrmMain_CmbSysContreventementStat_SelectedIndex"]));
            }
            set {
                this["FrmMain_CmbSysContreventementStat_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsShowHint_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsShowHint_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsShowHint_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtWg_Text {
            get {
                return ((double)(this["FrmMain_TxtWg_Text"]));
            }
            set {
                this["FrmMain_TxtWg_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsXiCustomValue_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsXiCustomValue_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsXiCustomValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsRCustomValue_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsRCustomValue_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsRCustomValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsT1T2CustomValue_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsT1T2CustomValue_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsT1T2CustomValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsQCustomValue_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsQCustomValue_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsQCustomValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsACustomValue_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsACustomValue_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsACustomValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmOptions_ChkIsBetaCustomValue_Checked {
            get {
                return ((bool)(this["FrmOptions_ChkIsBetaCustomValue_Checked"]));
            }
            set {
                this["FrmOptions_ChkIsBetaCustomValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FrmOptions_NumDuration_Value {
            get {
                return ((int)(this["FrmOptions_NumDuration_Value"]));
            }
            set {
                this["FrmOptions_NumDuration_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FrmOptions_NumPrecesion_Value {
            get {
                return ((int)(this["FrmOptions_NumPrecesion_Value"]));
            }
            set {
                this["FrmOptions_NumPrecesion_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtWq_Text {
            get {
                return ((double)(this["FrmMain_TxtWq_Text"]));
            }
            set {
                this["FrmMain_TxtWq_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtHn_Text {
            get {
                return ((double)(this["FrmMain_TxtHn_Text"]));
            }
            set {
                this["FrmMain_TxtHn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtLx_Text {
            get {
                return ((double)(this["FrmMain_TxtLx_Text"]));
            }
            set {
                this["FrmMain_TxtLx_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtLy_Text {
            get {
                return ((double)(this["FrmMain_TxtLy_Text"]));
            }
            set {
                this["FrmMain_TxtLy_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtSegma_Text {
            get {
                return ((double)(this["FrmMain_TxtSegma_Text"]));
            }
            set {
                this["FrmMain_TxtSegma_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtXiValeur_Text {
            get {
                return ((double)(this["FrmMain_TxtXiValeur_Text"]));
            }
            set {
                this["FrmMain_TxtXiValeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtRValeur_Text {
            get {
                return ((double)(this["FrmMain_TxtRValeur_Text"]));
            }
            set {
                this["FrmMain_TxtRValeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtT1Valeur_Text {
            get {
                return ((double)(this["FrmMain_TxtT1Valeur_Text"]));
            }
            set {
                this["FrmMain_TxtT1Valeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtT2Valeur_Text {
            get {
                return ((double)(this["FrmMain_TxtT2Valeur_Text"]));
            }
            set {
                this["FrmMain_TxtT2Valeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtQValeur_Text {
            get {
                return ((double)(this["FrmMain_TxtQValeur_Text"]));
            }
            set {
                this["FrmMain_TxtQValeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtAValeur_Text {
            get {
                return ((double)(this["FrmMain_TxtAValeur_Text"]));
            }
            set {
                this["FrmMain_TxtAValeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FrmMain_TxtBetaValeur_Text {
            get {
                return ((double)(this["FrmMain_TxtBetaValeur_Text"]));
            }
            set {
                this["FrmMain_TxtBetaValeur_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmOptions_CmbDeclarationduZone_SelectedIndex {
            get {
                return ((int)(this["FrmOptions_CmbDeclarationduZone_SelectedIndex"]));
            }
            set {
                this["FrmOptions_CmbDeclarationduZone_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item0 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item0"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item1 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item1"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item2 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item2"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item3 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item3"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item4 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item4"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item5 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item5"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmQualite_ChkLstQualite_Item6 {
            get {
                return ((bool)(this["FrmQualite_ChkLstQualite_Item6"]));
            }
            set {
                this["FrmQualite_ChkLstQualite_Item6"] = value;
            }
        }
    }
}
